eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka
      
spring:
  application:
    name: User-Service
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: gopal
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
server:
  port: 8084